### ISSUE TITLE
Apple M1 issue

### ISSUE THREAD

**Issue by robmarkcole** [aws/aws-mwaa-local-runner#1]
Hardware: MacBook Pro (13-inch, M1, 2020), Apple M1
OS: Big Sur 11.2.3

At step 1: `./mwaa-local-env build-image`

Fails with error: 
```
 ERROR [ 7/13] RUN chmod u+x /bootstrap.sh && /bootstrap.sh 
....
2dd0ca/pandas-1.1.0.tar.gz (5.2MB)
#12 28.13     Complete output from command python setup.py egg_info:
#12 28.13     Traceback (most recent call last):
#12 28.13       File "<string>", line 1, in <module>
#12 28.13       File "/tmp/pip-build-4qbofay4/pandas/setup.py", line 788, in <module>
#12 28.13         setup_package()
#12 28.13       File "/tmp/pip-build-4qbofay4/pandas/setup.py", line 758, in setup_package
#12 28.13         ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
#12 28.13       File "/tmp/pip-build-4qbofay4/pandas/setup.py", line 515, in maybe_cythonize
#12 28.13         raise RuntimeError("Cannot cythonize without Cython installed.")
#12 28.13     RuntimeError: Cannot cythonize without Cython installed.
#12 28.13     
#12 28.13     ----------------------------------------
#12 28.18 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4qbofay4/pandas/
```

I flag this as an M1 issue as this error is not raised on my non M1 Macbook.

To attempt to resolve I added `cython` to `docker/config/requirements.txt` but reach the same error

**Comment by jperkelens** [comment]
Also experiencing this in M1, I've worked around it by adding `Cython` to the `docker/scripts/bootstrap.sh` script. However that leads to a missing `numpy` package, and then to a missing `ffi.h` header. Worked around those by adding `numpy` to the bootstrap script and `libffi-devel` to the systemlibs script, respectively. I was then able to build the image successfully.
