### ISSUE TITLE
resetdb Error 

### ISSUE THREAD

**Issue by aliavni** [aws/aws-mwaa-local-runner#100]
I am getting the following error when I execute `./mwaa-local-env reset-db`

```
Error response from daemon: pull access denied for amazon/mwaa-local, 
repository does not exist or may require 'docker login': 
denied: requested access to the resource is denied
```

I am logged in to docker in my terminal, but I am not sure if this command requires specific resource permissions

**Comment by john-jac** [comment]
Tag is 2_2 as of 2.2.2
