### ISSUE TITLE
Image Support for MWAA Local Runner v1.10.15

### ISSUE THREAD

**Issue by animetauren** [aws/aws-mwaa-local-runner#11]
Requesting a release of MWAA Local Runner for Airflow v1.10.15. 

The reason is so that as customers are migrating from v1.10.12 to v2.0.x they can leverage this "Bridge" version to migrate their DAGs from 1.10.x to v2.0.x using several of the built in Airflow Upgrade Checks available on v1.10.15.

**Comment by cjames23** [comment]
I am going to try to get to this over the next few days to have a new version branch for 1.10.15 in a PR.
