### ISSUE TITLE
Cannot test python package installation using wheel

### ISSUE THREAD

**Issue by madhavdube** [aws/aws-mwaa-local-runner#120]
Hello, I am facing difficulty in testing python packages using wheel file. I have tried adding the wheel file in `plugins.zip` and adding that file under the newly created plugins folder.  Directory structure

```
├── README.md
├── dags
│   └── dummy.py
├── plugins
│   └── dummy-wheel-0.1.0-py3-none-any.whl
└── requirements.txt
```

After zipping the contents (only wheel file) the structure for directory `plugins` looks like

```
plugins
└── plugins.zip
```

Added the reference to the file in `requirements.txt` under `dags` folder as `/usr/local/airflow/plugins/dummy-wheel-0.1.0-py3-none-any.whl`

Error I get when I try to run `./mwaa-local-env test-requirements`
```
Container amazon/mwaa-local:2.0.2 exists. Skipping build
Installing requirements.txt
WARNING: Requirement '/usr/local/airflow/plugins/dummy-wheel-0.1.0-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./plugins/dummy-wheel-0.1.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/airflow/plugins/dummy-wheel-0.1.0-py3-none-any.whl'
```

**Comment by john-jac** [comment]
Addressed in 2.2.2
