### ISSUE TITLE
airflow.serialization.serialized_objects._TimetableNotRegistered: Timetable class 'uneven_intervals_timetable.UnevenIntervalsTimetable' is not registered

### ISSUE THREAD

**Issue by patelrahul766** [aws/aws-mwaa-local-runner#127]
**my Dag code: (dags/example.py)**
`
from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.bash import BashOperator
from uneven_intervals_timetable import UnevenIntervalsTimetable

default_args ={
	'owner': 'sri',
	'retries': 5,
	'retry_delay': timedelta(minutes=2)
}

with DAG(
	dag_id='dag_using_catchup_and_backfill_v3_timetable',
	default_args=default_args,
	description='this is the dag using backfill and catchup',
	start_date=datetime(2022, 5, 1),
	max_active_runs=1,
	timetable=UnevenIntervalsTimetable(),
	catchup=True
) as dag:
	task1 = BashOperator(
		task_id='first_task',
		bash_command="echo Hi Krishna"
	)
	task1`

**and Plugin code: (plugin/uneven_intervals_timetable.py)**

`
from datetime import timedelta
from typing import Optional
from pendulum import Date, DateTime, Time, timezone

from airflow.plugins_manager import AirflowPlugin
from airflow.timetables.base import DagRunInfo, DataInterval, TimeRestriction, Timetable

UTC = timezone("UTC")

class UnevenIntervalsTimetable(Timetable):

    def infer_manual_data_interval(self, run_after: DateTime) -> DataInterval:
        delta = timedelta(days=1)
        # If time is between 4:00 and 17:30, period ends at 4am and starts at 17:30 previous day
        if run_after >= run_after.set(hour=4, minute=0) and run_after <= run_after.set(hour=17, minute=30):
            start = (run_after-delta).set(hour=17, minute=30, second=0).replace(tzinfo=UTC)
            end = run_after.set(hour=4, minute=0, second=0).replace(tzinfo=UTC)
        # If time is after 17:30 but before midnight, period is between 4:00 and 17:30 the same day
        elif run_after >= run_after.set(hour=17, minute=30) and run_after.hour <= 23:
            start = run_after.set(hour=4, minute=0, second=0).replace(tzinfo=UTC)
            end = run_after.set(hour=17, minute=30, second=0).replace(tzinfo=UTC)
        # If time is after midnight but before 4:00, period is between 4:00 and 17:30 the previous day
        else:
            start = (run_after-delta).set(hour=4, minute=0).replace(tzinfo=UTC)
            end = (run_after-delta).set(hour=17, minute=30).replace(tzinfo=UTC)
        return DataInterval(start=start, end=end)

    def next_dagrun_info(
        self,
        *,
        last_automated_data_interval: Optional[DataInterval],
        restriction: TimeRestriction,
    ) -> Optional[DagRunInfo]:
        if last_automated_data_interval is not None:  # There was a previous run on the regular schedule.
            last_start = last_automated_data_interval.start
            delta = timedelta(days=1)
            if last_start.hour == 4: # If previous period started at 4:00, next period will start at 17:30 and end at 4:00 following day
                next_start = last_start.set(hour=17, minute=30).replace(tzinfo=UTC)
                next_end = (last_start+delta).replace(tzinfo=UTC)
            else: # If previous period started at 17:30, next period will start at 4:00 next day and end at 17:30
                next_start = (last_start+delta).set(hour=4, minute=0).replace(tzinfo=UTC)
                next_end = (last_start+delta).replace(tzinfo=UTC)
        else:  # This is the first ever run on the regular schedule. First data interval will always start at 6:00 and end at 16:30
            next_start = restriction.earliest
            if next_start is None:  # No start_date. Don't schedule.
                return None
            if not restriction.catchup: # If the DAG has catchup=False, today is the earliest to consider.
                next_start = max(next_start, DateTime.combine(Date.today(), Time.min).replace(tzinfo=UTC))
            next_start = next_start.set(hour=4, minute=0).replace(tzinfo=UTC)
            next_end = next_start.set(hour=17, minute=30).replace(tzinfo=UTC)
        if restriction.latest is not None and next_start > restriction.latest:
            return None  # Over the DAG's scheduled end; don't schedule.
        return DagRunInfo.interval(start=next_start, end=next_end)

class UnevenIntervalsTimetablePlugin(AirflowPlugin):
    name = "uneven_intervals_timetable_plugin"
    timetables = [UnevenIntervalsTimetable]
`

I am getting below error 
`airflow.serialization.serialized_objects._TimetableNotRegistered: Timetable class 'uneven_intervals_timetable.UnevenIntervalsTimetable' is not registered

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/serialization/serialized_objects.py", line 935, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.7/site-packages/airflow/serialization/serialized_objects.py", line 847, in serialize_dag
    raise SerializationError(f'Failed to serialize DAG {dag.dag_id!r}: {e}')
airflow.exceptions.SerializationError: Failed to serialize DAG 'dag_using_catchup_and_backfill_v3_timetable': Timetable class 'uneven_intervals_timetable.UnevenIntervalsTimetable' is not registered
`

I am using mwaa 2.2.2 env. in WSL Ubuntu. Can you please suggest what is wrong here?

**Comment by btruong66** [comment]
Hello @patelrahul766 were you able to resolve this? I am facing the same issue.

**Comment by patelrahul766** [comment]
> 
No, I did not find any solution to this problem.

**Comment by john-jac** [comment]
Ensure your timetable class is at the top level, unzipped, in local-runner plugins and that it loads correctly.  Closing as this does not seem to be a local-runner issue

**Comment by MemphisMeng** [comment]
@john-jac Hello, can you elaborate on what is "top level"? Does it mean that I need to put the custom `TimeTable` classes under the root folder of airflow?

**Comment by beramod** [comment]
@john-jac Can you answer MemphisMeng's question?
