### ISSUE TITLE
error while installing airflow.providers.cncf.kubernetes 

### ISSUE THREAD

**Issue by chandra-verana** [aws/aws-mwaa-local-runner#128]
airflow.providers.cncf.kubernetes requires apache-airflow >=2.3.0 and this is breaking the dag. I added it in requirements.txt but it is erroring out. As the current airflow version is 2.0.2 this packages has problems while installing. Is there any workaround for this?

**Comment by adm-huboo** [comment]
any update on this?

**Comment by john-jac** [comment]
See https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-eks-example.html#eksctl-requirements
