### ISSUE TITLE
"aws-mwaa-local-runner-2.0.2" is not a valid project name

### ISSUE THREAD

**Issue by samLozier** [aws/aws-mwaa-local-runner#131]
```
❯ ./mwaa-local-env start
"aws-mwaa-local-runner-2.0.2" is not a valid project name
```
I've been using this repo off and on for several months and I'm not sure what would have changed here, but I'm getting an error that the project name is invalid. to test it I've modified that  line (link below) in the shell script to remove the version spec (2.0.2) and now it works. To be clear, version name == aws-mwaa-local-runner works 

https://github.com/aws/aws-mwaa-local-runner/blob/main/mwaa-local-env#L4

**Comment by william-hopkins-tile** [comment]
I can replicate both the initial problem, and the fix @samLozier suggested. I just cloned the repo today, and have not used it before, so I can't speak to whether it worked previously.

**Comment by PythonZero** [comment]
Just got the same error too and fixed it with @samLozier's comment.

The fix:
On line 4, replace `DOCKER_COMPOSE_PROJECT_NAME=aws-mwaa-local-runner-$AIRFLOW_VERSION` with `DOCKER_COMPOSE_PROJECT_NAME=aws-mwaa-local-runner`

**Comment by bryzgaloff** [comment]
May depend on `docker-compose` version. I have encountered the same issue with `v2.6.0` (latest now): https://github.com/docker/compose/releases/tag/v2.6.0

`aws-mwaa-local-runner-test` worked for me.

**Comment by ym-sshukla** [comment]
I was facing same problem, based on my observation, I realised that this issue is because of dot (".") in name, which seems to be not supported by latest version of docker compose. I tried following option (used underscore instead dot).  
`DOCKER_COMPOSE_PROJECT_NAME=aws-mwaa-local-runner-2_0_2`

**Comment by sefremovR** [comment]
The small instruction from my side (thanks @ym-sshukla):
1. Open the `aws-mwaa-local-runner` folder
2. Open `mwaa-local-env` in a text editor like Notepadd++/Sublime Text
3. In the row 3 change `AIRFLOW_VERSION=2.0.2` to `AIRFLOW_VERSION=2_0_2`
4. Save the file and run the command `./mwaa-local-env start` once again

**Comment by reddy-s** [comment]
I faced the same issue. Happy to raise a PR if needed.

**Comment by cmpadden** [comment]
> The small instruction from my side (thanks @ym-sshukla):
> 
> 1. Open the `aws-mwaa-local-runner` folder
> 2. Open `mwaa-local-env` in a text editor like Notepadd++/Sublime Text
> 3. In the row 3 change `AIRFLOW_VERSION=2.0.2` to `AIRFLOW_VERSION=2_0_2`
> 4. Save the file and run the command `./mwaa-local-env start` once again

You will likely have to update the `docker/docker-compose-local.yml` file as well:

```
> git diff docker/docker-compose-local.yml
diff --git a/docker/docker-compose-local.yml b/docker/docker-compose-local.yml
index 054ab70..a54d83d 100644
--- a/docker/docker-compose-local.yml
+++ b/docker/docker-compose-local.yml
@@ -14,7 +14,7 @@ services:
             - "${PWD}/db-data:/var/lib/postgresql/data"

     local-runner:
-        image: amazon/mwaa-local:2.0.2
+        image: amazon/mwaa-local:2_0_2
         restart: always
         depends_on:
             - postgres
```

**Comment by john-jac** [comment]
Note that this has been fixed with https://github.com/aws/aws-mwaa-local-runner/pull/153 and version 2.2.2
