### ISSUE TITLE
Cannot install `pyarrow` in docker of Apple M1 Mac

### ISSUE THREAD

**Issue by mhadole-tc** [aws/aws-mwaa-local-runner#136]
One of our team members has experienced issues installing  pyarrow package in the `2.0.2`MWAA local runner (Device used:t Apple M1 Mac). It is working as expected in Intel Macs.
 

Following is the `requirements.txt`

```
botocore==1.20.106
Flask-OAuthlib==0.9.5
mysql-connector==2.2.9
mysqlclient==1.3.6
sql-metadata==1.5.0
snowflake-sqlalchemy==1.1.16
great_expectations==0.13.26
PyMySQL==0.9.3
dbt-core==1.0.7
dbt-snowflake==1.0.1
pyyaml==5.4
pysftp==0.2.9
fsspec==2021.7.0
s3fs==2021.7.0
tldextract
croniter
pyarrow==3.0.0
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
google-auth

asn1crypto==1.3.0
apache-airflow-providers-mysql
apache-airflow-providers-snowflake
apache-airflow-providers-amazon
snowflake-connector-python==2.4.1
apache-airflow[slack]==2.0.2
airflow-dbt==0.4.0

sshtunnel==0.1.5
black
```

Error
[local_runner_logs.log](https://github.com/aws/aws-mwaa-local-runner/files/8890376/local_runner_logs.log)

**Comment by gperiottomeli** [comment]
Do you have any solution?

**Comment by ghost** [comment]
> Do you have any solution?

I recently went through getting mwaa local runner running on an M1 macbook so I could develop locally before testing in a real mwaa environment. I had various issues with v2.0.2. Ultimately, even after all of the following steps, the workers failed to start, and it seemed like an issue with celery but don't quote me on that as I didn't dig into it. The following steps allowed me to get v2.2.2 up and running on my M1. I realize this is not a 1:1 for a 2.0.2 mwaa environment.

1. `git checkout v2.2.2`
2. `export DOCKER_DEFAULT_PLATFORM=linux/amd64` in your shell. [solves issue 171 ](https://github.com/aws/aws-mwaa-local-runner/issues/171)
3. build the docker image according the readme `./mwaa-local-env build-image`
4. add your requirements to `requirements/requirements.txt`. Previously it was `dags/requirements.txt` but it was not installing any requirements from there when I tried this today.
5. test the requirements
