### ISSUE TITLE
./mwaa-local-env build-image fails

### ISSUE THREAD

**Issue by haorans1994** [aws/aws-mwaa-local-runner#142]
I'm using windows and downloaded Docker desk and set up it to use WSL 2 engine. I used git bash to run 

./mwaa-local-env build-image

I get this error:

> #11 [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh
> #11 sha256:cce848dd2b45023b1179c67d53b90ad311bbf212f8c6f16a17eaa1c051023f90
> #11 0.360 /bin/sh: /systemlibs.sh: /bin/sh^M: bad interpreter: No such file or directory
> #11 ERROR: executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126
> ------
>  > [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh:
> ------
> executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126

Some files are missing from somewhere but I don't know which and what. Could you help me with it?

**Comment by haorans1994** [comment]
Use Ubuntu to run the command

**Comment by thongvhoang** [comment]
> I'm using windows and downloaded Docker desk and set up it to use WSL 2 engine. I used git bash to run
> 
> ./mwaa-local-env build-image
> 
> I get this error:
> 
> > ## #11 [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh
> > #11 sha256:cce848dd2b45023b1179c67d53b90ad311bbf212f8c6f16a17eaa1c051023f90
> > #11 0.360 /bin/sh: /systemlibs.sh: /bin/sh^M: bad interpreter: No such file or directory
> > #11 ERROR: executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126
> > > [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh:
> > 
> > 
> > 
> > executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126
> 
> Some files are missing from somewhere but I don't know which and what. Could you help me with it?

I have the same issue. How do you think I could fix it?
I used the Linux in Windows Subsystem Linux in Windows.
Thank you.

**Comment by thongvhoang** [comment]
> I'm using windows and downloaded Docker desk and set up it to use WSL 2 engine. I used git bash to run
> 
> ./mwaa-local-env build-image
> 
> I get this error:
> 
> > ## #11 [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh
> > #11 sha256:cce848dd2b45023b1179c67d53b90ad311bbf212f8c6f16a17eaa1c051023f90
> > #11 0.360 /bin/sh: /systemlibs.sh: /bin/sh^M: bad interpreter: No such file or directory
> > #11 ERROR: executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126
> > > [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh:
> > 
> > 
> > 
> > executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 126
> 
> Some files are missing from somewhere but I don't know which and what. Could you help me with it?

You can use the command: 
`sed -i 's/\r//' docker/script/systemlibs.sh` 
It worked for me
