### ISSUE TITLE
Upgrade python version in AWS Apache Airflow (MWAA)

### ISSUE THREAD

**Issue by ghost** [aws/aws-mwaa-local-runner#145]
Hello!

I am working with Apache Airflow in AWS (MWAA) and I have deployed a python package that was developed on python 3.8. It was running fine locally, however, on MWAA it starts giving syntax errors probably because the python version in MWAA is 3.7. Is there any possibility to upgrade the python version in MWAA or any workaround for this?

Thank you!

**Comment by john-jac** [comment]
MWAA, and by extension local-runner, currently only support Python 3.7.  Later Python versions will be available in subsequent MWAA releases.
