### ISSUE TITLE
Graceful restart of Airflow celery workers in MWAA

### ISSUE THREAD

**Issue by Shadowsong27** [aws/aws-mwaa-local-runner#146]
Hi we are using the latest v2.2.2 MWAA, 

We have one (and potentially) more libraries to handle dynamic task generation, but every deployment of said libs can only be updated with a full restart of all components in Airflow, resulting all running task entered a zombie state.

where with the self-hosted version we could restart the other components like schedulers first to make the dynamic DAG parsed, while keeping the existing task to continue to run before gracefully shutdown and restart celery workers.

Are there plans in MWAA to support a smoother environment update process?

**Comment by john-jac** [comment]
While we cannot comment directly on MWAA roadmap items the MWAA team is working to improve all aspects of environment management.
