### ISSUE TITLE
does anyone at AWS support this repository?

### ISSUE THREAD

**Issue by bgrinsted** [aws/aws-mwaa-local-runner#154]
Loads of issues, no responses from repo owners/contributors.

**Comment by AndrewLane** [comment]
Yeah it seems I'm running into lots of issues that are fixed in PRs that have been open for months :-/.

**Comment by bgrinsted** [comment]
@AndrewLane - this is why we're looking at Astronomer.io
@o-nikolas please raise this with the MWAA lead engineer.

**Comment by john-jac** [comment]
Note that 2.2.2 is the current version, and there have been a number of additions made to that version.  Further, local-runner is intended to reflect the libraries present on MWAA.  As MWAA releases new versions, so too will local-runner.  We cannot make changes to local-runner that are not present in MWAA, which many of the issues raised are requesting.  Note that we do take note of those issues should they apply to MWAA.
