### ISSUE TITLE
not able to install pymssql package in aws-mwaa-local-runner on Apple M1 Chip

### ISSUE THREAD

**Issue by janardhan1947** [aws/aws-mwaa-local-runner#158]
Hi Team,
I am not able to install pymssql package in aws-mwaa-local-runner on Apple M1 Chip. it is throwing below error.

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t26q1u0_/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t26q1u0_/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x2635l5t/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /usr/local/airflow/.local/include/python3.7m/pymssql
         cwd: /tmp/pip-install-t26q1u0_/pymssql/
    Complete output (32 lines):
    /usr/lib/python3.7/site-packages/setuptools/dist.py:44: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    setup.py: platform.system() => 'Linux'
    setup.py: platform.architecture() => ('64bit', '')
    /tmp/pip-install-t26q1u0_/pymssql/setup.py:160: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
      print("setup.py: platform.linux_distribution() => %r" % (platform.linux_distribution(),))
    setup.py: platform.linux_distribution() => ('', '', '')
    setup.py: platform.libc_ver() => ('glibc', '2.17')
    setup.py: Not using bundled FreeTDS
    setup.py: include_dirs = ['/usr/local/include']
    setup.py: library_dirs = ['/usr/local/lib']
    WARNING: The wheel package is not available.
    running install
    running build
    running build_ext
    cythoning src/_mssql.pyx to src/_mssql.c
    /usr/local/airflow/.local/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-t26q1u0_/pymssql/src/_mssql.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: src/_mssql.pyx:150:4: Exception already a builtin Cython type
    cythoning src/pymssql.pyx to src/pymssql.c
    /usr/local/airflow/.local/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-t26q1u0_/pymssql/src/pymssql.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    building '_mssql' extension
    creating build
    creating build/temp.linux-aarch64-3.7
    creating build/temp.linux-aarch64-3.7/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -moutline-atomics -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/include -I/usr/include/python3.7m -c src/_mssql.c -o build/temp.linux-aarch64-3.7/src/_mssql.o -DMSDBLIB
    src/_mssql.c:747:10: fatal error: sqlfront.h: No such file or directory
     #include "sqlfront.h"
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t26q1u0_/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t26q1u0_/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x2635l5t/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /usr/local/airflow/.local/include/python3.7m/pymssql Check the logs for full command output.
[airflow@3be827a54b59 ~]$ ls /usr/local/bin/

**Comment by sungjk1991** [comment]
Same issue here. But does actual MWAA have problem with it also? It seems like constraint file explictly pymssql==2.2.2 but I am having same issue as above on mwaa-local-runner.

**Comment by john-jac** [comment]
Note that local-runner is intended to reflect the same libraries as MWAA, which is running in an Amazon Linux OS on an AWS Fargate container.  It is possible that some libraries may not be compatible on other operating systems and architectures.
