### ISSUE TITLE
fixing permissions on existing directory /var/lib/postgresql/data ... initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted 

### ISSUE THREAD

**Issue by aws-sagar** [aws/aws-mwaa-local-runner#16]
## Issue
I was trying to run `./mwaa-local-env start `and it would throw below error.

## Error
aws-mwaa-local-runner git/main  20s
❯ ./mwaa-local-env start      
Starting docker_postgres_1 ... done
Starting docker_local-runner_1 ... done
Attaching to docker_postgres_1, docker_local-runner_1
postgres_1      | chmod: /var/lib/postgresql/data: Operation not permitted
postgres_1      | The files belonging to this database system will be owned by user "postgres".
postgres_1      | This user must also own the server process.
postgres_1      |
postgres_1      | The database cluster will be initialized with locale "en_US.utf8".
postgres_1      | The default database encoding has accordingly been set to "UTF8".
postgres_1      | The default text search configuration will be set to "english".
postgres_1      |
postgres_1      | Data page checksums are disabled.
postgres_1      |
postgres_1      | fixing permissions on existing directory /var/lib/postgresql/data ... initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
docker_postgres_1 exited with code 1
local-runner_1  | Fri Jun 11 18:48:08 UTC 2021 - waiting for Postgres... 1/20

## To replicate
I'm running this on my windows machine, below are the details of the host OS

aws-mwaa-local-runner git/main* 
❯ uname -a
Linux SEA-5CG021B68D 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

aws-mwaa-local-runner git/main* 
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

## Fix
Fix seemed easy enough, 
This can be fixed by modifying the docker-compose-local.yml file from this:
```
volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data"
```
to this:
```
volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data:z"
```
Essentially you are adding "z" at the end.

Source: https://stackoverflow.com/a/31334443

**Comment by subashcanapathy** [comment]
Thank you for raising this, looks to be reproduceable on any WSL setup. 

Tagging @o-nikolas for further review.

**Comment by JamesMDorame** [comment]
I'm experiencing this issue on Windows 10 WSL2 Ubuntu 20.04.  I have change the line in the docker-compose-local.yaml to be - "${PWD}/db-data:/var/lib/postgresql/data:Z" however when it tries to start the error still occurs:  
21T13:29:48.628934900Z chmod: /var/lib/postgresql/data: Operation not permitted

initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted

The only way I got it to work was to comment out the volume command in the docker file for Postgres

**Comment by john-jac** [comment]
`/var/lib` is not writable in local-runner nor MWAA

**Comment by jplauri** [comment]
> `/var/lib` is not writable in local-runner nor MWAA

I'm confused - what's the proper action based on this conclusion then? I tried adding ":z", ":Z" and omitting the whole volume-section from the yml file, but I still seem to get operation not permitted. I mean, shouldn't the yml be modified if /var/lib is not writable?

**Comment by mkrnr** [comment]
I'm facing the same issue after doing the initial setup on an M1 mac and agree with @jplauri. @john-jac can you explain why this issue was closed as completed?

**Comment by SergioFaya** [comment]
Same issue, windows 11 running WSL2, tried the same docker-compose file on MACand works as usual but the solution with the z didn't work for me

**Comment by vasisht24** [comment]
@SergioFaya Were you able to fix it?

I'm facing the same issue

**Comment by manugarri** [comment]
@JamesMDorame commenting the volume works, however I found that the user is not created then, did you experience the same?

@john-jac  why was this issue closed? its still an issue in WSL2

**Comment by robeche** [comment]
so... was this finally fixed in the end? why is it closed if so many people is asking?

**Comment by SashiDareddy** [comment]
try the fix suggested in https://stackoverflow.com/a/72416210 - you basically need to create a docker volume and edit the docker file as shown in the above SO answer

**Comment by philcampeau** [comment]
Thanks so much! This worked for me!

**Comment by PDJ5KOR** [comment]
It's working the solutions which provided above. Thanks a lot ! It save my day.
