### ISSUE TITLE
There is an incorrect FAQ about adding a requirement inside the README.md file for the v2.2.2 branch

### ISSUE THREAD

**Issue by jurgler** [aws/aws-mwaa-local-runner#164]
Adding requirements to dags/requirements.txt does not work.

According to the install_requirements inside the docker/script/entrypoint.sh, We should add the libraries to requirements/requirements.txt instead of the dags/requirements.txt

[https://github.com/aws/aws-mwaa-local-runner/blob/v2.2.2/docker/script/entrypoint.sh](url)
`# Global defaults
: "${REQUIREMENTS_FILE:="requirements/requirements.txt"}"

...'

'# Install custom python package if requirements.txt is present
install_requirements() {
    # Install custom python package if requirements.txt is present
    if [[ -e "$AIRFLOW_HOME/$REQUIREMENTS_FILE" ]]; then
        echo "Installing requirements.txt"
        pip3 install --user -r "$AIRFLOW_HOME/$REQUIREMENTS_FILE"
    fi
}`

**Comment by john-jac** [comment]
Fixed
