### ISSUE TITLE
Not a valid project name

### ISSUE THREAD

**Issue by jtruong-godaddy** [aws/aws-mwaa-local-runner#168]
Following along with the instructions and when trying to start the image post build with ./mwaa-local-env start, docker throws an error of ""aws-mwaa-local-runner-2.0.2" is not a valid project name".

Environment:
  Windows 10 w/ WSL 2
  Docker Desktop 4.12.0 (Engine 20.10.17, Compose 2.10.2)

**Comment by john-jac** [comment]
Addressed for default branch in https://github.com/aws/aws-mwaa-local-runner/pull/153
