### ISSUE TITLE
Upgrade Boto3 in docker/config/requirements.txt instead of creating a new requirements.txt file

### ISSUE THREAD

**Issue by anselboero** [aws/aws-mwaa-local-runner#175]
Hi,
As I'd like to use boto3 emr-serverless service, I need to upgrade boto3 library to the latest version, as unfortunately version 1.18.65 doesn't support it.
I tried to update the following file [docker/config/requirements.txt](https://github.com/aws/aws-mwaa-local-runner/blob/v2.2.2/docker/config/requirements.txt) and then to build the image but the version inside the container was still the v1.18.65. I read that we can add Python dependencies by creating a new file at the following path dags/requirements.txt, but (maybe I'm wrong) I understood that dependencies are loaded at "runtime".

Is there a way to upgrade some python libraries while building the image?
Thank you very much for your help

**Comment by john-jac** [comment]
Local-runner is meant to reference MWAA, which in turn uses the default Airflow constraints.
