### ISSUE TITLE
API requests not working

### ISSUE THREAD

**Issue by RP-kaiopedroza** [aws/aws-mwaa-local-runner#177]
Hi there,

I'm trying to use the API to create connections and variables but I keep geeting the same error:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/86850063/196760887-ec87e62d-166a-40af-a887-0d158fde92c3.png">

I tried to change the ´auth_backends´ to default with no success.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/86850063/196761255-e8980469-5d1c-47fa-9d2e-555b7d9a2ac6.png">

**Comment by GuyMcComb** [comment]
Hi There,

If you look at the documentation around the API on the airflow [site](https:`//airflow.apache.org/docs/apache-airflow/stable/security/api.html) it states `You can only disable authentication for experimental API, not the stable REST API.` You will have to just use `backend.basic_auth` and pass a user name and password if you are using `curl`.

**Comment by john-jac** [comment]
Local-runner is meant to reflect MWAA, which currently does not support the Airflow REST API
