### ISSUE TITLE
README instructions misleading

### ISSUE THREAD

**Issue by shulai** [aws/aws-mwaa-local-runner#180]
Hi.

Unless I'm completely wrong the instructions in the README are misleading. It says: 

> Add Python dependencies to dags/requirements.txt.

And then again: 

> Let's say you add aws-batch==0.6 to your dags/requirements.txt file.

However `./mwaa-local-env test-requirements` doesn't process `dags/requirements.txt` but `requirements/requirements.txt` instead.

**Comment by Haebuk** [comment]
I think so.
