### ISSUE TITLE
SYSTEM_DEPS and PYTHON_DEPS fail with multiple packages specified

### ISSUE THREAD

**Issue by breiter** [aws/aws-mwaa-local-runner#183]
In `docker/Dockerfile` there are ARG variables defined for `SYSTEM_DEPS` and `PYTHON_DEPS` which are used in `docker/scripts/systemlibs.sh` and `docker/scripts/bootstrap.sh` respectively.

In both cases the variables are quoted which causes the `docker build` to fail if multiple values are specified separated by spaces. 

Example:

In Dockerfile set SYSTEM_DEPS

```
ARG SYSTEM_DEPS="tar wget gzip gcc make expect"
```

When `docker build` runs, and gets to line 33 in systemlibs.sh `if [ -n "${SYSTEM_DEPS}" ]; then yum install -y "${SYSTEM_DEPS}"; fi` it will fail because there is no package called "tar wget gzip gcc make expect".

The solution is to remove the quoting around `${SYSTEM_DEPS}` to allow splitting the package names passed to yum on the spaces.

```diff
diff --git a/docker/script/systemlibs.sh b/docker/script/systemlibs.sh
index 48ef0ca..3a66b2d 100644
--- a/docker/script/systemlibs.sh
+++ b/docker/script/systemlibs.sh
@@ -30,6 +30,6 @@ yum install -y nc
 yum install -y python2-cryptography
 
 # Install additional system library dependencies. Provided as a string of libraries separated by space
-if [ -n "${SYSTEM_DEPS}" ]; then yum install -y "${SYSTEM_DEPS}"; fi
+if [ -n "${SYSTEM_DEPS}" ]; then yum install -y ${SYSTEM_DEPS}; fi
 
 yum clean all
\ No newline at end of file
```

```diff
diff --git a/docker/script/bootstrap.sh b/docker/script/bootstrap.sh
index 575d9ed..74563b0 100644
--- a/docker/script/bootstrap.sh
+++ b/docker/script/bootstrap.sh
@@ -20,7 +20,7 @@ pip3 install $PIP_OPTION psycopg2
 pip3 install $PIP_OPTION --constraint /constraints.txt apache-airflow[crypto,celery,statsd"${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}"]=="${AIRFLOW_VERSION}"
 
 # install additional python dependencies
-if [ -n "${PYTHON_DEPS}" ]; then pip3 install $PIP_OPTION "${PYTHON_DEPS}"; fi
+if [ -n "${PYTHON_DEPS}" ]; then pip3 install $PIP_OPTION ${PYTHON_DEPS}; fi
 
 # install adduser and add the airflow user
 adduser -s /bin/bash -d "${AIRFLOW_USER_HOME}" airflow
```

**Comment by john-jac** [comment]
All MWAA-used packages are currently represented and as such SYSTEM_DEPS, etc are not used.  local-runner is only intended to reflect the state of MWAA, not be a general-purpose Airflow package.  As such, this edit is not required but may be considered for a future version.
