### ISSUE TITLE
amazon/mwaa-local:2_2 Image doesn't exist

### ISSUE THREAD

**Issue by osmandi** [aws/aws-mwaa-local-runner#184]
Hi, the base docker image does not exist on docker hub. It's like it's been removed.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/30201113/201996871-f472f140-b62c-42f4-a097-1ef7c67b996c.png">

**Comment by vinayvaddiparthi** [comment]
@osmandi  You need to first build the image locally using `./mwaa-local-env build-image`

**Comment by osmandi** [comment]
Thanks, it works for me
