### ISSUE TITLE
airflow command line support

### ISSUE THREAD

**Issue by JStolt** [aws/aws-mwaa-local-runner#19]
It's not explicitly called out in the readme, but I would expect the airflow command line tool to be available as well.  When attempting to run airflow commands on the container, I received the following provider error:
```
[airflow@6fabad976155 ~]$ airflow --version
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/airflow/__init__.py", line 34, in <module>
    from airflow import settings
  File "/usr/local/lib/python3.7/site-packages/airflow/settings.py", line 37, in <module>
    from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 1098, in <module>
    conf = initialize_config()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 860, in initialize_config
    conf.validate()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 199, in validate
    self._validate_config_dependencies()
  File "/usr/local/lib/python3.7/site-packages/airflow/configuration.py", line 240, in _validate_config_dependencies
    f"error: sqlite C library version too old (< {min_sqlite_version}). "
airflow.exceptions.AirflowConfigException: error: sqlite C library version too old (< 3.15.0). See https://airflow.apache.org/docs/apache-airflow/2.0.2/howto/set-up-database.rst#setting-up-a-sqlite-database
```

It looks like a library reference needs to be updated somewhere, but I'm not sure if it's here or the underlying amazonlinux image.  Or, maybe there's a way to avoid the `apache-airflow-providers-sqlite` dependency completely as this uses a postgres backend?  Guidance or a fix would be appreciated, thanks!

**Comment by JStolt** [comment]
I did some more digging today and it looks like container sqlite3 version = 3.7.17, so that should be good.  I guess I'm not sure why [_validate_config_dependencies](https://github.com/apache/airflow/blob/7af18ac856b470f91e75d419f27e78bc2a0b215b/airflow/configuration.py#L222) is still triggering with the sql_alchemy_conn=sqlite://{AIRFLOW_HOME}/airflow.db line commented out in the AF config and the executor being sequential.

**Comment by ashley-mallia** [comment]
Hi @JStolt,

Take a look at the PR I just raised which gets around the immediate issue.
You are right though, I don't see why apache-airflow-providers-sqlite is needed when the database being used here is postgresql.

**Comment by ashley-mallia** [comment]
It appears that AIRFLOW__CORE__SQL_ALCHEMY_CONN is not exported when running docker exec 
so when running airflow cli, it is actually using the default connections strings and therefore thinking that mysql is being used.

In `docker-compose-local.yml` I defined `AIRFLOW__CORE__SQL_ALCHEMY_CONN`, after this airflow cli will run

```
    local-runner:
        image: amazon/mwaa-local:2.0
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
```

**Comment by SergiyKolesnikov** [comment]
Airflow CLI commands can be run using `entrypoint.sh` script (which sets up the required environment). For example to list DAGs run:
```
docker-compose -f docker/docker-compose-local.yml exec -- local-runner /entrypoint.sh airflow dags list
```

**Comment by bradthurber** [comment]
I am very new to airflow and Sergiy's comment on how to use the airflow command line was really helpful. Should it be integrated into the repo home page markdown instructions so that others can know about it? I am happy to write a pull request if that is the best way to get it there and it makes sense.

**Comment by austin-chou** [comment]
Not sure if anyone has this issue, but I did all the steps mentioned above, but when I run the command in my terminal, I don't get any output, was wondering if anyone else encountered this issue?

To be more specific, it would appear that I'm getting a:
`Failed to log action with (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known`

**Comment by smigielp** [comment]
After adding following line to `docker-compose-local.yml` I still have problems starting local runner:
`AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow`

The logs look like this:

```
Attaching to docker_postgres_1, docker_local-runner_1
postgres_1      | 
postgres_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1      | 
postgres_1      | 2022-06-04 13:16:30.690 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1      | 2022-06-04 13:16:30.690 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1      | 2022-06-04 13:16:30.694 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1      | 2022-06-04 13:16:30.704 UTC [21] LOG:  database system was shut down at 2022-06-04 13:16:17 UTC
postgres_1      | 2022-06-04 13:16:30.707 UTC [1] LOG:  database system is ready to accept connections
local-runner_1  | Sat Jun  4 13:16:31 UTC 2022 - waiting for Postgres... 1/20
local-runner_1  | Sat Jun  4 13:16:36 UTC 2022 - waiting for Postgres... 2/20
local-runner_1  | Sat Jun  4 13:16:41 UTC 2022 - waiting for Postgres... 3/20
```

Anyone came across sth like that?

**Comment by ym-sshukla** [comment]
I was also facing this issue and after following this thread and many tries I am able to run Airflow CLI commands now. 
please follow these set of instructions:
1. Open the `airflow.cfg` file and make sure following line is not commented:
    `result_backend = db+postgresql://postgres:airflow@postgres/airflow`
2. in airflow.cfg comment the next line that is for mysql db:
    `# result_backend = db+mysql://airflow:airflow@localhost:3306/airflow`
3. In `docker-compose-local.yml` add `AIRFLOW__CORE__SQL_ALCHEMY_CONN` as shown in last line of code snippet below:
```
        local-runner:
        image: amazon/mwaa-local:2.0.2
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
```
4. Save the file and run the command ./mwaa-local-env start once again

**Comment by john-jac** [comment]
Airflow CLI is accessible via `docker exec -it xxxxxxxxxxxxxxxxxxxxxxxx /bin/sh` in local runner
