### ISSUE TITLE
How to import helper functions?

### ISSUE THREAD

**Issue by phifa** [aws/aws-mwaa-local-runner#194]
In my dags I use helper functions that I always store in `./include/foo.py`. How do I make this folder known to the local runner?

**Comment by elashrry** [comment]
I think if you named the folder `include` to `plugins`, you will have access to `foo.py` by the code `from foo import boo` in your dags without any modification to the scripts provided.

**Comment by phifa** [comment]
i just tried this, but it doesn't work. 


./plugins/utils.py
```
def chunkList(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i : i + n]
```


./dags/mydag.py
```
from utils import chunkList


@dag(
    schedule_interval="@daily",
...
```

**Comment by elashrry** [comment]
could you please add more information, logs, and steps to reproduce the issue?

**Comment by phifa** [comment]
i resolved it by adding all my files, including my helper files in the dag folder like so: 
```
./dags/include/utils.py
```
