### ISSUE TITLE
Default credentials not working on tag v2.4.3

### ISSUE THREAD

**Issue by ghost** [aws/aws-mwaa-local-runner#210]
```
By default, the bootstrap.sh script creates a username and password for your local Airflow environment.

Username: admin
Password: test
```

This doesn't work for me, I've tested this with both Chromium and Firefox.

I get this log after resetting the db with `./mwaa-local-env reset-db` but it does not tell me with which password the user was added.

```
local-runner_1  | [2023-02-13 15:36:45,772] {{manager.py:212}} INFO - Added user admin
```

**Comment by wang-lx** [comment]
I have the same problem. admin/test doesn't work. The page will show ```Invalid login. Please try again.```. Could anyone help to fix this?

**Comment by toddy86** [comment]
There is a bug. If you look at the terminal output, it will show that the creation of the `admin` user actually fails. Short of actually fixing the code, the quick "hack" is to simple open a shell inside the container and create the user manually.

```
./mwaa-local-env shell
airflow users create -r Admin -u admin -e admin@example.com -f admin -l user -p admin
```

**Comment by matiaspirovanovarela** [comment]
This is also happening on tag v2.5.1.

@toddy86 I wasn't able to run `./mwaa-local-env shell` and I couldn't find the shell command in the script nor the history. May I ask what tag or version are you using?

**Comment by toddy86** [comment]
@matiaspirovanovarela, I'm on 2.2.2

Ah, and the `shell` command doesn't exist natively (my bad). This is something we implemented. 

We wrap everything into a make file. So to access the shell, just run something like

```
docker-compose -p aws-mwaa-local-runner-2_2 -f ./docker/docker-compose-local.yml run --rm local-runner bash
```
(obviously edit for your specific version etc)

**Comment by mjsqu** [comment]
DEFAULT_PASSWORD="test"

https://github.com/aws/aws-mwaa-local-runner/blob/v2.4.3/docker/config/.env.localrunner#L8

The password includes the quotes

**Comment by mayushko26** [comment]
deduping: https://github.com/aws/aws-mwaa-local-runner/issues/300
