### ISSUE TITLE
v2.4.3 build-image fails while installing MariaDB

### ISSUE THREAD

**Issue by kalyanr23** [aws/aws-mwaa-local-runner#211]
I get the following error when doing
`./mwaa-local-env build-image`
I haven't modified anything in the repo. I just cloned and tried to build it.
 ```
sudo rpm -ivh /mariadb_rpm/MariaDB-common-10.8.6-1.el7.centos.x86_64.rpm /mariadb_rpm/MariaDB-compat-10.8.6-1.el7.centos.x86_64.rpm /mariadb_rpm/MariaDB-devel-10.8.6-1.el7.centos.x86_64.rpm /mariadb_rpm/MariaDB-shared-10.8.6-1.el7.centos.x86_64.rpm
#0 221.2 warning: /mariadb_rpm/MariaDB-common-10.8.6-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID c74cd1d8: NOKEY
#0 221.2 error: Failed dependencies:
#0 221.2        libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-common-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libdl.so.2(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libm.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libpthread.so.0(GLIBC_2.3.2)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        librt.so.1(GLIBC_2.2.5)(64bit) is needed by MariaDB-compat-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-devel-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.14)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.3.4)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.3)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libc.so.6(GLIBC_2.4)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libdl.so.2(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libm.so.6(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
#0 221.2        libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by MariaDB-shared-10.8.6-1.el7.centos.x86_64
------
ERROR: failed to solve: executor failed running [/bin/sh -c chmod u+x /bootstrap.sh && /bootstrap.sh]: exit code: 4
(base) SEQMAC-GLQ4WFJ200:aws-mwaa-local-runner kalyan.reddy$ 
```

**Comment by dpolamarasetty** [comment]
I got the same error as well. Appreciate some help with this issue

**Comment by dpolamarasetty** [comment]
@kalyanr23  In the docker/script/bootstrap.sh  file i commented out the mairadb stuff and it worked for me 

#sudo mkdir mariadb_rpm
#sudo chown airflow /mariadb_rpm
#wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-amd64/rpms/MariaDB-common-10.8.6-1.el7.centos.x86_64.rpm -P /mariadb_rpm
#wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-amd64/rpms/MariaDB-compat-10.8.6-1.el7.centos.x86_64.rpm -P /mariadb_rpm
#wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-amd64/rpms/MariaDB-shared-10.8.6-1.el7.centos.x86_64.rpm -P /mariadb_rpm
#wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-amd64/rpms/MariaDB-devel-10.8.6-1.el7.centos.x86_64.rpm -P /mariadb_rpm

# install mariadb_devel and its dependencies
#sudo rpm -ivh /mariadb_rpm/*

**Comment by hunnybear** [comment]
Same issue, would appreciate something working in mainline

**Comment by rawwar** [comment]
@dpolamarasetty , for local, I did that and it worked. But, we need to be sure if our requirements work on prod. Would appreciate if the issue is fixed.

**Comment by john-jac** [comment]
MWAA local runner was pulling MariaDB images from a dal.ca mirror.  It is possible that domain is blocked from some global regions.

It is now updated to pull from the mariadb.com domain instead.  Please pull the latest Github version to see if that addresses the issue.

**Comment by linczakjw** [comment]
I did a clone of this v2.4.3 just now (after the commit from @john-jac above) and I'm still getting this issue.  I'm on an Mac with an M1 (ARM) if that's helpful.

**Comment by kalyanr23** [comment]
> I did a clone of this v2.4.3 just now (after the commit from @john-jac above) and I'm still getting this issue. I'm on an Mac with an M1 (ARM) if that's helpful.

Same here.

**Comment by edgarasnavickas** [comment]
Having the same issue on M1 Mac too.

**Comment by johnnypez** [comment]
Having the same issue on Apple Silicon.

I figured the problem might be down to the architecture being hardcoded for the mariadb packages starting here https://github.com/aws/aws-mwaa-local-runner/blob/v2.4.3/docker/script/bootstrap.sh#L51

I changed those lines to use the aarch64 build and the image builds ok.

```bash
wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-aarch64/rpms/MariaDB-common-10.8.4-1.el7.centos.aarch64.rpm -P /mariadb_rpm
wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-aarch64/rpms/MariaDB-compat-10.8.4-1.el7.centos.aarch64.rpm -P /mariadb_rpm
wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-aarch64/rpms/MariaDB-shared-10.8.4-1.el7.centos.aarch64.rpm -P /mariadb_rpm
wget https://mirror.its.dal.ca/mariadb/yum/10.8/centos7-aarch64/rpms/MariaDB-devel-10.8.4-1.el7.centos.aarch64.rpm -P /mariadb_rpm
```

The image builds ok then.

The next issue is in the docker-compose-local.yml where platform is set to `linux/amd64` here https://github.com/aws/aws-mwaa-local-runner/blob/v2.4.3/docker/docker-compose-local.yml#L18

I just commented that out and I was able to run `./mwaa-local-env start` successfully.

I hope this helps.
