### ISSUE TITLE
Excessive resource usage on arch

### ISSUE THREAD

**Issue by drawnwren** [aws/aws-mwaa-local-runner#219]
I'm not sure what the problem is exactly, but:
```
./mwaa-local-env build-image
./mwaa-local-env start
```

On Arch, this takes 100% of my 5900HX processing power and all 16 gigs of RAM. Completely freezes the system, and I've left it on for 12 hours -- so it's not like it's some build task that it's completing.

**Comment by pejc** [comment]
This is a wider issue than just this repository. Here is a discussion with solutions from the Airflow repo:
https://github.com/apache/airflow/discussions/29731#discussioncomment-5162421
