### ISSUE TITLE
mwaa-local-env build-image fails at chown -R airflow: /usr/local/airflow

### ISSUE THREAD

**Issue by korrigan43** [aws/aws-mwaa-local-runner#223]
I'm trying to install the aws-mwaa-local-runner in my environment and it fails at step 13/15: it stays stuck on the following command:
RUN chown -R airflow: /usr/local/airflow

I'm using latest version of Docker Desktop for Windws, WSL 2 is up-to-date. I'm using ubuntu 20.4 on WSL2 to run the script.

**Comment by choudrybabu** [comment]
can you please let me know how were you able to resolve this issue @korrigan43 ?
I am having same trouble running the build-image command with v2.7.2 and the image fails at the same chown step 
**RUN chown -R airflow /usr/local/airflow:
0.211 chown: invalid user: 'airflow'**
it first failed at running all .sh file i changed the commands as below and it went through 
```
RUN chmod u+x /systemlibs.sh && sed -i 's/\r//' /systemlibs.sh
RUN chmod u+x /bootstrap.sh && sed -i 's/\r//' /bootstrap.sh
RUN chmod u+x /generate_key.sh && sed -i 's/\r//' /generate_key.sh
```

**Comment by korrigan43** [comment]
Hi @choudrybabu,
I'm working from windows and all the bash scripts ended up having CR / LF symbol converted to windows system.
I edited all the .sh scripts in Notepad++ and used Edit > EOL Conversion > Unix

Hope it helps
