### ISSUE TITLE
227 only fixed for main branch(2.4.3) and not other tags

### ISSUE THREAD

**Issue by l-moamen** [aws/aws-mwaa-local-runner#229]
Continuing on [227](https://github.com/aws/aws-mwaa-local-runner/issues/227)
the issue only resolved for main, but not for tags, hence for runner 2.0.2 (and other tags) we can't locally test it! 

`./mwaa-local-env` build-image
[+] Building 5.5s (12/20)                                                                                                         
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 1.48kB                                                                                       0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/amazonlinux:latest                                                        1.2s
 => [auth] library/amazonlinux:pull token for registry-1.docker.io                                                           0.0s
 => [ 1/15] FROM docker.io/library/amazonlinux@sha256:85c8f169ab712d0c5f3fc6616b851b9b9ad0f895daf465fa1bcc95185697bf31       0.0s
 => [internal] load build context                                                                                            0.0s
 => => transferring context: 68.31kB                                                                                         0.0s
 => CACHED [ 2/15] COPY script/bootstrap.sh /bootstrap.sh                                                                    0.0s
 => CACHED [ 3/15] COPY script/systemlibs.sh /systemlibs.sh                                                                  0.0s
 => CACHED [ 4/15] COPY script/generate_key.sh /generate_key.sh                                                              0.0s
 => CACHED [ 5/15] COPY config/constraints.txt /constraints.txt                                                              0.0s
 => CACHED [ 6/15] COPY config/mwaa-base-providers-requirements.txt /mwaa-base-providers-requirements.txt                    0.0s
 => ERROR [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh                                                             4.3s

 > [ 7/15] RUN chmod u+x /systemlibs.sh && /systemlibs.sh:                                                                        
#12 1.663 Amazon Linux 2023 repository                     10 MB/s |  11 MB     00:01                                             
#12 3.639 Last metadata expiration check: 0:00:02 ago on Thu Mar 16 00:53:33 2023.                                                
#12 3.972 Dependencies resolved.                                                                                                  
#12 3.976 Nothing to do.                                                                                                          
#12 3.976 Complete!
#12 4.195 Last metadata expiration check: 0:00:03 ago on Thu Mar 16 00:53:33 2023.
#12 4.215 No match for argument: python37
#12 4.225 Error: Unable to find a match: python37

executor failed running [/bin/sh -c chmod u+x /systemlibs.sh && /systemlibs.sh]: exit code: 1`

**Comment by john-jac** [comment]
Change merged for older branches
