### ISSUE TITLE
MWAA branch 2.0.2 cannot start db

### ISSUE THREAD

**Issue by said-rasidin** [aws/aws-mwaa-local-runner#231]
I am using MWAA 2.0.2 and clone the branch for local env but I cannot start the airflow.
when command `./mwaw.. start` this error appears. how to Fix it
`alembic.util.exc.CommandError: Can't locate revision identified by '290244fb8b83'`

**Comment by mayushko26** [comment]
This happens when the requirements you install accidentally bump the version of apache-airflow. Constraining apache-airflow==1.10.12 should resolve this issue.
