### ISSUE TITLE
unable to start MWAA 1.10.x locally

### ISSUE THREAD

**Issue by toshilam** [aws/aws-mwaa-local-runner#232]
the MWAA postgres database in 1.10.x revision mismatch
`Can't locate revision identified by 'e07f49787c9d'`

by looking at the airflow website about data migration
https://airflow.apache.org/docs/apache-airflow/stable/migrations-ref.html
the revision 'e07f49787c9d' is for 2.x

local-runner_1  | The above exception was the direct cause of the following exception:
local-runner_1  | 
local-runner_1  | Traceback (most recent call last):
local-runner_1  |   File "/usr/local/bin/airflow", line 37, in <module>
local-runner_1  |     args.func(args)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 76, in wrapper
local-runner_1  |     return f(*args, **kwargs)
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 1221, in scheduler
local-runner_1  |     job.run()
local-runner_1  |   File "/usr/local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 212, in run
local-runner_1  |     session.commit()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
local-runner_1  |     self.transaction.commit()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
local-runner_1  |     self._prepare_impl()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
local-runner_1  |     self.session.flush()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
local-runner_1  |     self._flush(objects)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
local-runner_1  |     transaction.rollback(_capture_exception=True)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
local-runner_1  |     exc_value, with_traceback=exc_tb,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
local-runner_1  |     raise exception
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
local-runner_1  |     flush_context.execute()
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
local-runner_1  |     rec.execute(self)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
local-runner_1  |     uow,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
local-runner_1  |     insert,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
local-runner_1  |     statement, params
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
local-runner_1  |     return meth(self, multiparams, params)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
local-runner_1  |     return connection._execute_clauseelement(self, multiparams, params)
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
local-runner_1  |     distilled_params,
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
local-runner_1  |     e, statement, parameters, cursor, context
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
local-runner_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
local-runner_1  |     raise exception
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
local-runner_1  |     cursor, statement, parameters, context
local-runner_1  |   File "/usr/local/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
local-runner_1  |     cursor.execute(statement, parameters)
**local-runner_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job" does not exist
local-runner_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...**

**Comment by mayushko26** [comment]
This happens when the requirements you install accidentally bump the version of `apache-airflow`. Constraining `apache-airflow==1.10.12` should resolve this issue.
