### ISSUE TITLE
using startup.sh to add environment variables is not showing those within the DAGs

### ISSUE THREAD

**Issue by 094459** [aws/aws-mwaa-local-runner#244]
I am using the branch with the added local startup script support. When I rebuild my image, and create a new startup script:

```
export BUILD_ON_OPEN_SOURCE="awesome"
echo $BUILD_ON_OPEN_SOURCE

sudo yum install java-17-amazon-corretto-headless -y
```

The Amazon Corretto is installed as expected. The environment variable seems to work during the boot process (you see it output) but then when I try and view it within a DAG I get an empty value:

When I take the startup script and upload / configure an equiv mwaa environment, it works. To troubleshoot I added a new entry in the run-startup.sh to output the values of stored_env, and I can see the item listed

```
s-mwaa-local-runner-2_4-local-runner-1  | declare -x AIRFLOW_HOME="/usr/local/airflow"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AIRFLOW__CORE__EXECUTOR="LocalExecutor"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AIRFLOW__CORE__FERNET_KEY="IqDRu5ADgAltqc8_UmrIr0kqZ2MktW_clm6dIw6GAS0="
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AIRFLOW__CORE__LOAD_EXAMPLES="False"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AIRFLOW__CORE__SQL_ALCHEMY_CONN="postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AWS_ACCESS_KEY_ID="xxxxxxx"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x AWS_SECRET_ACCESS_KEY="xxxxxxxxx"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -- BASH="/usr/bin/bash"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -A BASH_ALIASES='()'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -a BASH_ARGC='()'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -a BASH_ARGV='()'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -A BASH_CMDS='()'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -- BASH_COMMAND
aws-mwaa-local-runner-2_4-local-runner-1  | declare -a BASH_LINENO='([0]="0")'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -a BASH_SOURCE='([0]="/run-startup.sh")'
aws-mwaa-local-runner-2_4-local-runner-1  | declare -- BASH_SUBSHELL
aws-mwaa-local-runner-2_4-local-runner-1  | declare -- BASH_VERSION="4.2.46(2)-release"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x BUILD_ON_OPEN_SOURCE="awesome"
aws-mwaa-local-runner-2_4-local-runner-1  | declare -- COMP_WORDBREAKS
aws-mwaa-local-runner-2_4-local-runner-1  | declare -x DEFAULT_PASSWORD="test"
```

So figuring this must be some issue with variables not being picked up.

**Comment by vishalvijay18** [comment]
Could you please share which branch you are seeing this issue? Did your script time-out?

**Comment by 094459** [comment]
https://github.com/aws/aws-mwaa-local-runner/tree/v2.4.3/startup_script

**Comment by 094459** [comment]
It doesn't time out. The issue is that the variable set is not available within the dag

**Comment by 094459** [comment]
I have been experimenting to try and see exactly where the environment variables "disappear". I altered the various scripts to echo out a single env variable I defined in the startup.sh script. This is what I found - as the function (execute_startup_script) is called, the environment variable is picked up all the way through the various sub-shells. However, when the function returns to the next line in the entry point script, it disappears.

![airflow-variables](https://user-images.githubusercontent.com/3873813/232483672-c4a615e6-f0be-498c-83e2-5764e3335f25.png)

**Comment by 094459** [comment]
I hasten to add, this DOES work on the MWAA managed service, so this issue is only on mwaa-local-runner. I have tried this now on my mac, my ubuntu desktop and a Cloud9 instance and they all do the same.

**Comment by 094459** [comment]
I have now got this working, but I am not sure this is the "right" thing to do. To fix, I modified the entrypoint.sh with the following:

```
    install_requirements
    execute_startup_script
    source stored_env    <-- added this
    airflow db init
```

Not sure if this is a proper solution as I note that in the actual execute_startup_script you call this and then export three AIRFLOW variables.
