### ISSUE TITLE
Support AWS MWAA REST API

### ISSUE THREAD

**Issue by tal181** [aws/aws-mwaa-local-runner#25]
Can you please add support for AWS MWAA REST API  ?
e.g  "${host}/aws_mwaa/cli"
body : 'pause my_dag'

**Comment by atishbits** [comment]
+1 this would be a good add-on to mimic the production MWAA setup locally

**Comment by john-jac** [comment]
The CLI API on MWAA is meant to replicate what you can do locally via 'docker exec -it xxxxxxxxxxxxxxxxxxxxxxxx /bin/sh' in local runner
