### ISSUE TITLE
When accessing remote S3 from local-runner, `Name or service not known` is displayed and access is not possible

### ISSUE THREAD

**Issue by briete** [aws/aws-mwaa-local-runner#256]
version: 2.5.1

I am trying to access remote S3 by launching local-runner to check DAG operation.

I created a Connection with local-runner and confirmed that I can AssumeRole to IAM Role.
Then, when I try to access remote S3 from the DAG using the `S3Hook` `get_key` function, I get the following error

```
Could not connect to the endpoint URL: "https://xxx.s3.ap-northeast-1.amazonaws.com/xxx.json"
```

It looks like name resolution is failing to begin with. This object exists and is the correct URL.

I believe the cause is probably name resolution failure in the case of `virtual-hosted-style` requests in S3. When I run curl in the Docker container to try it out, I get an error, but when I access it with S3 `path-style` requests, it appears to resolve the name successfully (since it shows AccessDenied).
Only in the case of S3's `Virtual-hosted-style` does name resolution seem to fail.

```
$ docker exec -it e4caa064c191 /bin/bash
[airflow@e4caa064c191 ~] curl https://xxx.s3.ap-northeast-1.amazonaws.com/yyy.json
curl: (6) Could not resolve host: xxx.s3.ap-northeast-1.amazonaws.com

[airflow@e4caa064c191 ~] curl https://s3.ap-northeast-1.amazonaws.com/xxx/yyy.json
<?xml version="1.0" encoding="UTF-8"? >
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>53QC679VD3JMWY79</RequestId><HostId>WuyOr7+C++hGSohx5CBn /RNBI4zF5jcqo/l+TMGLzsdKmNOvwrNgOXc5u0Sq6JJjNJczG1XXXXXX=</HostId></Error>
```

The host has confirmed that both can be accessed correctly.

How can I make it so that I can also access the S3 `virtual-hosted-style` from local-runner?

**Comment by mbb70** [comment]
Hi @briete, did you manage to figure out the issue? Running into similar problem. Appreciate any advice you can give!
