### ISSUE TITLE
plugins.zip generated by build-requirements giving issues on MWAA

### ISSUE THREAD

**Issue by kalyanr23** [aws/aws-mwaa-local-runner#257]
I have generated my plugins.zip using local-mwaa-runner. But, when i used it on my AWS MWAA, i got the following error

`
--
Looking in links: /usr/local/airflow/plugins
Processing ./plugins/apache_airflow_providers_snowflake-4.0.2-py3-none-any.whl
Processing ./plugins/apache_airflow_providers_mysql-4.0.0-py3-none-any.whl
ERROR: Cannot install tqdm==4.64.1 because these package versions have conflicting dependencies.
 
The conflict is caused by:
The user requested tqdm==4.64.1
The user requested (constraint) tqdm==4.64.1
 
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

But, my plugins.zip has these .whl files.

**Comment by mayushko26** [comment]
This is a misleading error which actually signals that the whl for `tqdm==4.64.1` is not compatible on the architecture the pip install is running on; so, it behaves as though it isn't there. Related to: https://github.com/aws/aws-mwaa-local-runner/issues/331

**Comment by mayushko26** [comment]
Closing for duplication
