### ISSUE TITLE
MWAA variables cannot be accessed in GUI if set in UI and vice-versa

### ISSUE THREAD

**Issue by DaniDasBoot** [aws/aws-mwaa-local-runner#27]
It appears that when the `FERNET_KEY` is set in entrypoint.sh, it is not persisted so the airflow CLI cannot access variables that are set for MWAA in the web UI. The `FERNET_KEY` should be persisted to airflow.cfg so that both the CLI and the UI can use the same key across sessions.

**Comment by ashley-mallia** [comment]
Possibly related to #29
