### ISSUE TITLE
Launching the Docker container fails with `pull access denied for amazon/mwaa-local` error

### ISSUE THREAD

**Issue by tjbeatty** [aws/aws-mwaa-local-runner#271]
Following the instructions in the README, the image builds just fine. However, when I try to run the local environment with `./mwaa-local-env start`, I get the following error immediately: 

```
✘ local-runner Error   
Error response from daemon: pull access denied for amazon/mwaa-local, repository 
does not exist or may require 'docker login': denied: requested access to the 
resource is denied
```

I know the image doesn't exist on Docker Hub, but I tried logging in anyway because it was a suggested fix, but that still (obviously) didn't work. 

I found [this related issue](https://github.com/aws/aws-mwaa-local-runner/issues/40) from a long time ago with possible workarounds, but this issue appears to still be occurring ~18 months later.

**Comment by tjbeatty** [comment]
No issue. There was an error on our part on a branched version of this. We were mixing and matching the branched version and the AWS managed version which lead to different version references.

**Comment by shawnazhaoxy** [comment]
Hi are you able to explain what is the exact issue, i am running v2.2.2, and is experiencing the same issue
