### ISSUE TITLE
Mention to amazon provider version 6.0.0 - Default version on AWS is 2.4.0

### ISSUE THREAD

**Issue by douglaszickuhr** [aws/aws-mwaa-local-runner#273]
The requirements file refer to a version that's not the default on MWAA v2.2.2 as can be shown on [official](https://docs.aws.amazon.com/mwaa/latest/userguide/connections-packages.html#connections-packages-table-222) documentation from Amazon.

https://github.com/aws/aws-mwaa-local-runner/blob/506d31bc0a1e7d9590f47f11aab8ef06aa4b5466/requirements/requirements.txt#L3

Shouldn't that be actually [apache-airflow-providers-amazon==2.4.0](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html) instead?

**Comment by Mercury2699** [comment]
This is because 6.0.0 is the highest version that supports Airflow 2.2.2.
So you can choose from any versions between the two, but ideally use the latest supported version.
Reference: https://airflow.apache.org/docs/apache-airflow-providers-amazon/6.0.0/index.html
