### ISSUE TITLE
MWAA local and the hosted does not have safeguards for auto updating airflow

### ISSUE THREAD

**Issue by shmcsensei** [aws/aws-mwaa-local-runner#278]
If the following constraint from the requirements.txt is removed there are no safeguards either in local MWAA or in the Amazon hosted airflow preventing an auto upgrade to the latest unsupported (unsupported by AWS) version of Airflow. i.e 2.6.x as of writing.

`--constraint "/usr/local/airflow/dags/constraints-3.7-amazon-6.0.txt"`

`--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.1/constraints-3.10.txt"`

This has happened to me and resulted in needing to rebuild the entire airflow environment as the only solution for rollback

**Comment by mayushko26** [comment]
This is one of the reasons constraints should always be used when installing python dependencies. This has been improved in MWAA environments for versions 2.6.3, onwards, but the local runner is somewhat less opinionated and has more freedom in the respect (and less safe-guards).
