### ISSUE TITLE
./mwaa-local-env build-image fails

### ISSUE THREAD

**Issue by ok512** [aws/aws-mwaa-local-runner#285]
Running on AWS workspace Ubuntu 22.04, got same result as [davetbo-amzn](https://github.com/aws/aws-mwaa-local-runner/issues/7#issuecomment-1475304659)

**curl http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list**
_https://cdn.amazonlinux.com/2/core/2.0/x86_64/95051b33cb06275a2be90f45ee8fbd12a95dc2afe7ba94bff90e197f4d6a9403_

curl https://cdn.amazonlinux.com/2/core/2.0/x86_64/95051b33cb06275a2be90f45ee8fbd12a95dc2afe7ba94bff90e197f4d6a9403
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>NE7V2WHK6JG5999Z</RequestId>
  <HostId>
x8dLJXRsK106CaHEBwKhjuOzXhfFpBodneRAhzlytkjMkMfk7S/NfeOAi8qDn20Sa70W5JOBGUo=
  </HostId>
</Error>
```

**Comment by dujjwalr-aws** [comment]
you can always reopen the original issue thread if you feel like issue is still going on. 
Keep the discussion in the same thread. 
closing this thread.

**Comment by ecc256** [comment]
> you can always reopen the original issue thread if you feel like issue is still going on.
How do I do it exactly?
