### ISSUE TITLE
Local Runner 2.5.1 does not enforce constraints

### ISSUE THREAD

**Issue by caldanaicode** [aws/aws-mwaa-local-runner#295]
Referring to the following:

https://github.com/aws/aws-mwaa-local-runner/blob/v2.5.1/docker/script/entrypoint.sh#L23-L36

Local runner only checks the existence of a requirements file, and issues a warning if there is no constraint, but constraints are not required. No default constraint is used if constraints are not provided.

- Requirements exist?
    - No grep -c?
        - No grep --constraint?
            - Issues a warning
    - Install requirements

**Comment by mayushko26** [comment]
This isn't a bug in the local runner. We allow you to use unconstrained requirements, though it is not recommended.
