### ISSUE TITLE
MWAA installing Python packages 

### ISSUE THREAD

**Issue by ashley-mallia** [aws/aws-mwaa-local-runner#30]
I see that this local runner allows for setting environment variables such as $PIP_OPTION $PYTHON_DEPS which are used during build-image.

Does the actual MWAA environment support using these variables?

**Comment by manypozo** [comment]
Maybe I am wrong, but my understanding is that there is no control or interaction with the actual MWAA environment hosted in AWS.

The only way to install dependencies would be using `requirements.txt`.  
I do not see a finer control over pip options other than the possible things under requirements.txt as well (for instance, adding --index-url)

requirements.txt
```
--index-url __my_url__
my_package_1
my_package_2
```

**Comment by o-nikolas** [comment]
> Maybe I am wrong, but my understanding is that there is no control or interaction with the actual MWAA environment hosted in AWS.
> 
> The only way to install dependencies would be using `requirements.txt`.
> I do not see a finer control over pip options other than the possible things under requirements.txt as well (for instance, adding --index-url)
> 
> requirements.txt
> 
> ```
> --index-url __my_url__
> my_package_1
> my_package_2
> ```

This is correct. We don't at this time allow setting arbitrary environment variables in MWAA.
