### ISSUE TITLE
How do you set connections and variables programmatically?

### ISSUE THREAD

**Issue by ylhan** [aws/aws-mwaa-local-runner#317]
I would like to set variables and connections programmatically so that they're automatically loaded into Airflow. I'm running 2.6.3 with the only change being adding the following to [`.env.localrunner`](https://github.com/aws/aws-mwaa-local-runner/blob/v2.6.3/docker/config/.env.localrunner). 
```
AIRFLOW_CONN_SLACK_CONN='my-conn-type://login:password@host:port/schema?param1=val1&param2=val2'
AIRFLOW_VAR_DEPLOY_ENVIRONMENT=qa
```
The problem is that both the variable and the connection don't show up in the UI. I've tried rebuilding from scratch and restarting the container. Am I setting these in the wrong place?

**Comment by ylhan** [comment]
It turns out I can access both the variable and the connection in my dag but they still don't show up in the UI - is this intentional?

**Comment by mayushko26** [comment]
You should do this in the startup script; `startup.sh`

**Comment by rhyek** [comment]
I tried setting a connection in both `.env.localrunner` and exporting in `startup.sh` and the connection never shows up in the Airflow UI. I can use the connection in a dag, however.

I'll also mention that I set `load_default_connections` to `False` in `airflow.cfg` and I still see the default list populated.
