### ISSUE TITLE
Is it possible to change the version?

### ISSUE THREAD

**Issue by JeongPock2y** [aws/aws-mwaa-local-runner#326]
I want to test it on mwaa 2.6.3.

Now, 2.7.2 is the default setting, so I would like to lower the version being checked.

**Comment by erg** [comment]
There are tags you can check out.

``git checkout v2.6.3``

**Comment by JeongPock2y** [comment]
@erg   Thank you so much ! mr.erg!   it's really helpful  for me!! haha

**Comment by mayushko26** [comment]
I'll add this in the README as it might not be clear. Closing this issue
