### ISSUE TITLE
running docker on local runner

### ISSUE THREAD

**Issue by asmksf** [aws/aws-mwaa-local-runner#33]
we are testing docker dag locally and have the dag file below and when 

default_args = {
'owner'                 : 'airflow',
'description'           : 'Use of the DockerOperator',
'depend_on_past'        : False,
'start_date'            : datetime(2021, 7, 28),
'email_on_failure'      : True,
'email_on_retry'        : False,
'retries'               : 0,
'retry_delay'           : timedelta(minutes=5)
}
dag = DAG('bash_docker_dag', default_args=default_args, schedule_interval="5 * * * *", catchup=False, tags= ['maf_opt_by_bin'])
t1 = BashOperator(
task_id='print_current_dir',
    bash_command='echo $(pwd)',
dag=dag
)
t3 = BashOperator(
task_id='test-job',
bash_command = '/usr/local/bin/docker run -v cmd " 

and when we trigger dag from console it shows docker 

[2021-07-28 15:03:11,253] {{bash.py:158}} INFO - Running command: docker run -v "CMD"
[2021-07-28 15:03:11,261] {{bash.py:169}} INFO - Output:
[2021-07-28 15:03:11,262] {{bash.py:173}} INFO - bash: docker: command not found
[2021-07-28 15:03:11,262] {{bash.py:177}} INFO - Command exited with return code 127

**Comment by salmaroohik** [comment]
1) In this line, I see different quotes (starts with single and end with double quotes). This could not be the cause, just trying to understand the syntax used in the dag file. 
bash_command = '/usr/local/bin/docker run -v cmd "

2) Have you been using the latest version of your requirements.txt file? The latest version of the requirement file has to be chosen from the drop down menu as shown in the image below.
![image](https://user-images.githubusercontent.com/66973650/127727295-74fb1bb4-1a61-4d3f-8bd4-20a7aff58ab7.png)

3) Would also like to take a look at your requirements.txt file to check if docker dependency has been defined.

**Comment by salmaroohik** [comment]
I got the fix which is working on my MWAA local runner. 

The provider, apache-airflow-providers-docker is not installed. Including this line in the requirements.txt of your dags folder would resolve the issue.

![image](https://user-images.githubusercontent.com/66973650/127924128-34e961ec-cb6d-43c0-85ec-b3d8b5422ee9.png)

**Comment by john-jac** [comment]
Running `/usr/local/bin/docker run -v cmd` is not supported on MWAA and as such is not supported on local-runner.
