### ISSUE TITLE
cdn.amazonlinux SSL certs needed

### ISSUE THREAD

**Issue by datocrats-org** [aws/aws-mwaa-local-runner#34]
I have a similar issue as https://github.com/aws/aws-mwaa-local-runner/issues/7# though I think it is related to SSL verification as opposed to an incorrect link can you provide some pointers on how to add the required SSL certs to validate the CDN.amazonlinux links?

OS: Ubuntu 2004 on WSL 1, Docker for Windows 20.10.2
Release: https://github.com/aws/aws-mwaa-local-runner/releases/tag/v2.0.2

```log
=> ERROR [ 6/13] RUN chmod u+x /systemlibs.sh && /systemlibs.sh                                                                             3.3s
------
 > [ 6/13] RUN chmod u+x /systemlibs.sh && /systemlibs.sh:
#10 1.192 Loaded plugins: ovl, priorities
#10 3.125 https://cdn.amazonlinux.com/2/core/2.0/x86_64/0c4b5094bba8d46b07c60e3d85cd8baac5f75d07af6a33086b6d0cd9eb2e13f1/repodata/repomd.xml?instance_id=URLError&region=unknown: [Errno 14] curl#60 - "SSL certificate problem: unable to get local issuer certificate"
```

**Comment by datocrats-org** [comment]
I got it to proceed / work with VPN disabled. It may help to keep it open here, though you can close it if you think that's enough of a fix for the purposes of us building things.  

Two asides:
1. It'd be helpful if you can build the image yourselves with your AWS magic powers, then put it on dockerhub or any AWS public facing docker image repo with security, that'd be helpful. Users could then modify it according to their needs perhaps by adding the credentials and region / account details they need.  
2. It'd be great to have some additional utilities to push directly from the local dev environment up to AWS.

**Comment by john-jac** [comment]
local-runner is not targeted for DockerHub availability, nor being pre-built.  However, that may be a consideration in the future.
