### ISSUE TITLE
Installing non-pip dependencies

### ISSUE THREAD

**Issue by justinwagg** [aws/aws-mwaa-local-runner#36]
I am running an Airflow task that requires `git` be installed. I'm using this image to test before running in mwaa.

I am receiving the error below indicating that git is not installed. 

```bash
[2021-08-04 02:51:37,820] {{bash.py:158}} INFO - Running command: git --version
[2021-08-04 02:51:37,881] {{bash.py:169}} INFO - Output:
[2021-08-04 02:51:37,902] {{bash.py:173}} INFO - bash: git: command not found
[2021-08-04 02:51:37,902] {{bash.py:177}} INFO - Command exited with return code 127
```

I see `bootstrap.sh` in this repo, adding `yum install git -y` solves the issue, however I can not find a way of providing a bootstrap script in the production image. 

Am I overlooking this or is this a feature request?

Thanks!

**Comment by wdoug** [comment]
This is from the [MWAA FAQ](https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-faqs.html):

> ### Can I use a custom image for my Amazon MWAA environment?
> Custom images are not supported. Amazon MWAA uses images that are built on Amazon Linux AMI. Amazon MWAA installs the additional requirements by running pip3 -r install for the requirements specified in the requirements.txt file you add to the Amazon S3 bucket for the environment.

As far as I can tell this means there currently is no way to install dependencies that can't be installed with pip.

We also require a dependency for our DAGs that can't be installed with pip (in our current specific case it is `ffmpeg`). Without this, we may be forced to abandon our adoption of MWAA. 

I would assume this would be a very common need/request for folks to use MWAA. Is there any information on if there are plans to support some way to install other dependencies or use a custom docker image for the workers in MWAA? If there are plans, is there any expectation on what the timeline might be for that capability?

**Comment by shaibruhis** [comment]
Any update here? I also have a dependency in my requirements file that installs from a git branch

**Comment by Gatsby-Lee** [comment]
I have the same issue.

**Comment by johnchuckcase** [comment]
If you only need to install python dependencies from a private repo, you can try pushing your repo to a private PyPi service like Gemfury. [See option three under the best practices section](https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html#best-practices-dependencies-custom-auth-url).

This doesn't solve the need for custom system-level dependencies though. It would be great to have custom docker image support!

**Comment by SurajitChowbey** [comment]
Stuck in same place, need to install GDAL

**Comment by SurajitChowbey** [comment]
seems MWAA does not care about it

**Comment by john-jac** [comment]
>I see bootstrap.sh in this repo, adding yum install git -y solves the issue, however I can not find a way of providing a bootstrap script in the production image.

MWAA as a managed service does not modification of the Airflow image.  local-runner reflects those limitations.  A workaround is to use plugins i.e. https://docs.aws.amazon.com/mwaa/latest/userguide/samples-oracle.html

> We also require a dependency for our DAGs that can't be installed with pip (in our current specific case it is ffmpeg). 

The Airflow community recommends using Airflow as an orchestrator.  It is not recommended to run the actual workloads on the Airflow workers, and definitely not encoding/decoding video.  Recommend using an external container i.e.https://docs.aws.amazon.com/mwaa/latest/userguide/samples-ecs-operator.html

Closing as this forum is dedicated to issues specific to local-runner.  Please see the Airflow Slack #airflow-aws for additional support.

**Comment by carsongregory** [comment]
https://docs.aws.amazon.com/mwaa/latest/userguide/using-startup-script.html

Can be used to install system level dependencies.
