### ISSUE TITLE
Request to Update constraint.txt File

### ISSUE THREAD

**Issue by paolarozovgs** [aws/aws-mwaa-local-runner#360]
Hello all,

The constraint.txt file needs to be updated in the local-runner repository. Given the recent update to Airflow version 3.8.1, it's imperative to ensure compatibility with the latest dependencies.

Specifically, I've noticed that libraries such as Flask-AppBuilder need to be updated to version 4.3.10 or higher for compatibility with Airflow 3.8.1. Therefore,  the constraint.txt file should be updated accordingly.

**Comment by mayushko26** [comment]
https://github.com/aws/aws-mwaa-local-runner/pull/362
