### ISSUE TITLE
Update for MWAA v2.8.1

### ISSUE THREAD

**Issue by GergelyKalmar** [aws/aws-mwaa-local-runner#361]
The latest branch is currently v2.7.2, however, we already have AWS MWAA v2.8.1 released. This means that when a cluster has been upgraded the requirements files are not compatible with aws-mwaa-local-runner, and local development is not possible anymore. This needs to be corrected ASAP. We would expect AWS to also update this important tool when releasing a new version.

**Comment by mayushko26** [comment]
2.8.1 support will be released by end of day. Local runner support is always done as a fast-follow to the official release.

**Comment by mayushko26** [comment]
https://github.com/aws/aws-mwaa-local-runner/pull/362

**Comment by GergelyKalmar** [comment]
Works fine, thank you very much!
