### ISSUE TITLE
Error when mwaa-local start

### ISSUE THREAD

**Issue by TAKEDA-Takashi** [aws/aws-mwaa-local-runner#366]
Error when `./mwaa-local-env start`.

Operating System: macOS Sonoma
Error message:
```
$ ./mwaa-local-env start
[+] Running 1/1
 ✘ local-runner Error                                                                                                   12.4s
Error response from daemon: pull access denied for amazon/mwaa-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

I accessed the following URL from a web browser, but the page was not found.

https://hub.docker.com/r/amazon/mwaa-local

Will the repository be revived? Are there any alternative measures?

**Comment by guyb-orca** [comment]
if you have an M1 processor, the image was probably built with `arm64` architecture and not `amd64` as specified in the `docker-compose-local.yml` file. 
you have two options:

1. re-build the image as `amd64`
2. change the the following line in the `docker-compose-local.yml` file from `platform: "linux/amd64"` to `platform: "linux/arm64"`.

**Comment by TAKEDA-Takashi** [comment]
Thank you.
I ended up running it in the new environment and it worked.
Was it irrelevant that the URL was not visible in the browser?
