### ISSUE TITLE
Run with config not working from ui .

### ISSUE THREAD

**Issue by narayanshivansh49** [aws/aws-mwaa-local-runner#38]
I am not able to change the default params by passing config in the UI.
> Tested this locally on the mwaa-local-runner as well as on AWS cloud.

### Minimal Code for Reproducing Error

```python3
from datetime import datetime, timedelta

from airflow.models.dag import DAG
from airflow.operators.python import PythonOperator


def dummy_run_spark(**context):
    import pprint

    from random import randint
    from time import sleep
    config = context["params"]
    pprint.pprint(type(config))
    pprint.pprint(context["task"].task_id)
    pprint.pprint(context)
    sleep(randint(1, 10))


default_params = {
    "name": "Jhon"
}

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(year=2018, month=7, day=10),
    "email": ["airflow@airflow.com"],
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(seconds=10),
    "catchup": False,
    "params": default_params,
}

with DAG(
        'Testing',
        default_args=default_args,
        schedule_interval=None,
 
) as dag:

    t1 = PythonOperator(task_id='t1',
                                provide_context=True,
                                python_callable=dummy_run_spark,)
```

For the above dag if I pass params as 
`{
    "name": "Jhon Doe"
}`
The logs still show the name as Jhon

**This however works on the official airflow docker image (Version 2.0.2). On the official image I can change the default params from UI and the same is reflected on the logs as well** 

> I am checking the params passed by logging few stuff in the function `def dummy_run_spark(**context):`

**Comment by shivansh-narayan** [comment]
We were able to solve this by passing "core.dag_run_conf_overrides_params	True" in environment .

**Comment by ferrouswheel** [comment]
Instead of closing this issue, could someone from AWS please explain why they changed the default Airflow value?
