### ISSUE TITLE
amazonlinux SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by jabjakub** [aws/aws-mwaa-local-runner#382]
hi All,

I've been trying to build a docker image for a really long time but it does not work...I'm getting errors on Ubuntu18.04 which is my VM running in VPN.

Errors during downloading metadata for repository 'amazonlinux':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.4.20240416/x86_64/mirror.list [SSL certificate problem: self-signed certificate in certificate chain]
Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.4.20240416/x86_64/mirror.list [SSL certificate problem: self-signed certificate in certificate chain]
Ignoring repositories: amazonlinux

I checked and it works on another machine (Mac) with no issues and I spins it up instantly. 

It would be great if you were able to push me to the correct direction....

**Comment by garsirw1** [comment]
Hello @jabjakub do you remember how you managed to solve this in the end?

**Comment by peterx6** [comment]
Hi @jabjakub , how did you fix this? I faced exactly same issue recently
