### ISSUE TITLE
Can't access Airflow UI with defaults

### ISSUE THREAD

**Issue by awong-s** [aws/aws-mwaa-local-runner#39]
```
By default, the bootstrap.sh script creates a username and password for your local Airflow environment.

Username: admin
Password: test
```
This doesn't work for me!

**Comment by ukayani** [comment]
can confirm, this does not work for me either. It looks like the db user does not get populated.

**Comment by ukayani** [comment]
@awong-s , in my case it turned out it was just not working with Safari. Chrome works.

**Comment by mark-welsh** [comment]
this is also not working for me regardless of which browser I use

**Comment by awong-s** [comment]
@ukayani  thanks. 
works with chrome for me.
