### ISSUE TITLE
"snowflake" not showing up in conn_type Dropwdown

### ISSUE THREAD

**Issue by hayderimran7** [aws/aws-mwaa-local-runner#42]
Hi im using MWAA airflow 2.0.2 and have following (redacted) `requirements.txt`  
```
apache-airflow-providers-snowflake==1.3.0
snowflake-connector-python==2.4.6
snowflake-sqlalchemy==1.2.4
```
but even after all deps are installed the "Snowflake" conn_type is not showing in dropdown under "Admin -> Connections"

**Comment by rodrigoSun** [comment]
Same behavior here, even if it is not listed you can use an HTTP connection type, set the host, username, and password, and on the `extra` field:
```
{
    "account": "YOURACCOUNT",
    "database": "YOUR_DATABASE"
}
```

and you are gonna be good to go

**Comment by john-jac** [comment]
https://docs.aws.amazon.com/mwaa/latest/userguide/connections-packages.html
