### ISSUE TITLE
Airflow connection returns 500

### ISSUE THREAD

**Issue by smitthakkar1** [aws/aws-mwaa-local-runner#44]
When I open `Admin > Connections`, it throws 500 Internal Server Error, Below is the screenshot. I am on branch`v2.0.2`. 

![image](https://user-images.githubusercontent.com/17807868/130647133-aea42e3c-0a3c-400d-bdc2-5dbba231a782.png)

**Comment by kevinggrimm** [comment]
What are the log outputs for your `local-runner_1`? For instance these are the outputs when I do the same:
```bash
local-runner_1  | 172.27.0.1 - - [24/Aug/2021:20:18:02 +0000] "GET /connection/list/ HTTP/1.1" 200 98812 "http://localhost:8080/home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
```
Are there any errors in your logs?

**Comment by john-jac** [comment]
Not reproducible in latest 2.2.2 version
