### ISSUE TITLE
Postgresql would not start from a Windows WSL2 host - could not change permissions

### ISSUE THREAD

**Issue by bradthurber** [aws/aws-mwaa-local-runner#45]
Full disclosure I don't really know what I am doing with docker or airflow but wanted to post this in case it helped another Windows user use this project. I was able to build just fine but when running `./mwaa-local-env start` it would fail starting postgres_1 with the error:

`fixing permissions on existing directory /var/lib/postgresql/data ... initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted`

Following these steps allowed postgres and then airflow to load

1. `docker volume create --name=db-data` to create a db-data volume in docker

1. In file `./docker/docker-compose-local.yml` change the line 
 `- "${PWD}/db-data:/var/lib/postgresql/data"`
 to
 `- "/db-data:/var/lib/postgresql/data"`

I am not sure what side-effects this will have for me. I suppose I can't access the postgres data files from the windows filesystem but I don't think I need to do that anyway.

**Comment by bradthurber** [comment]
Well forget all of that I guess. My main misstep was crossing file systems - which is not recommended (1). 

When opening the WSL2 Ubuntu terminal it defaults to a Windows filesystem folder. By simply typing `cd ~` I am in my home directory under the linux filesystem(1). From there, I can follow the `aws-mwaa-local-runner` "Get Started" instructions as written and they work great. No `docker volume create` needed. No modification to `docker-compose-local.yml` needed.

(1) https://docs.microsoft.com/en-us/windows/wsl/compare-versions#performance-across-os-file-systems

**Comment by garrett-groff-ch** [comment]
@bradthurber - Huge credit to you for these instructions, which were linked from SO (link: https://stackoverflow.com/questions/71096132/aws-mwaa-postgres-not-reachable-error-when-trying-to-run-a-local-apache-airfl/72416210#72416210).

Yes, you're correct that the line endings had to be changed -- which I did. However, I still had to use your proposed solution above to get past the postgres issue. So thank you for your earlier write-up.

I hope that the main project's github readme someday includes a note on the line endings issue and also somehow fixes the `docker-compose-local.yml` file to work in Windows, without breaking other OSes.
