### ISSUE TITLE
Change CLI language from Shell to something more robust

### ISSUE THREAD

**Issue by yehoshuadimarsky** [aws/aws-mwaa-local-runner#5]
Love this project and a huge fan of Airflow, containers, and cloud in general. I think we can make this CLI/runner better by moving away from pure shell scripts and instead implementing the CLI in a more robust way, such as using a language like Python or Go for this. I'd be happy to contribute to that effort with PRs etc, creating the issue here first to track it.

### Some ideas:

- [Astronomer](https://www.Astronomer.io) has a really great CLI (written in Golang) that I've personally used many times to spin up an Airflow instance locally for dev and testing. It uses a few Docker containers under the hood. The CLI has a lot more things it can do, but I think the part that's of interest to us is just the commands in the `astro dev` section. I believe this is the link to the relevant source code for that subsection of their CLI; perhaps we could adopt something similar. https://github.com/astronomer/astro-cli/tree/v0.23.4/airflow
- Alternatively we could use Python and Click to quickly put it together. I suspect that most of the folks reading this are far more comfortable in Python than Golang, so it would be a lot easier. The only downside is that you'd need to install it as a Python package, as opposed to the Golang one which is vended as a single executable binary file.

**Comment by john-jac** [comment]
local-runner is intended to test requirements and plugins ahead of deployment to MWAA.  It is not intended to be a robust Airflow deployment in and of itself.
