### ISSUE TITLE
Airflow Providers Google dependencies doesn't work

### ISSUE THREAD

**Issue by quangthai351** [aws/aws-mwaa-local-runner#55]
I had issue after install apache-airflow-providers-google==5.1.0 (latest) .

When I started the Airflow webserver it doesn't let me access to Connection page.

**Comment by ldocao-decathlon** [comment]
Starting from v4.0, this package requires Airflow 2.1+ . The current version of MWAA supports Airflow 2.0.2. You thus cannot use 5.1.0 package.

https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html#id10

I tried to downgrade to 3.0.0 but encountered a problem while installing dependencies (plyvel and leveldb)

**Comment by john-jac** [comment]
2.2.2 is available and default
