### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by ldocao-decathlon** [aws/aws-mwaa-local-runner#58]
When you try to import any google libraries via 

```python
from google.cloud import bigquery
ModuleNotFoundError: No module named 'google'
```

I was surprised because we can see in the `constraints.txt` 

google-cloud-bigquery==1.28.0

Is this a bug?

**Comment by mayankshah891** [comment]
we're also having this issue. Running MWAA and added google modules (googleapiclient, google, etc) but none seem to work. All other modules/processes working fine

**Comment by john-jac** [comment]
Please add to requirements.txt

https://docs.aws.amazon.com/mwaa/latest/userguide/t-apache-airflow-11012.html#missing-bigquery-cython
