### ISSUE TITLE
reset-db: incorrect image

### ISSUE THREAD

**Issue by elliotdes** [aws/aws-mwaa-local-runner#63]
Having some issues when calling `./mwaa-local-env reset-db`. Error:
```shell
Pulling resetdb (amazon/mwaa-local:2.0)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```

I think this is due to this line:

https://github.com/aws/aws-mwaa-local-runner/blob/f34a1b6c3c118933b5ee7d4f7d34605bf54f6001/docker/docker-compose-resetdb.yml#L17

Could this be fixed by changing it to use image `amazon/mwaa-local:2.0.2`?

**Comment by IanHopkinson** [comment]
The fix proposed works

**Comment by john-jac** [comment]
tag is 2_2 as of 2.2.2
