### ISSUE TITLE
bootstrap.sh fails when installing apache-airflow 2.0.2

### ISSUE THREAD

**Issue by cdang1234** [aws/aws-mwaa-local-runner#80]
<img width="1109" alt="Screen Shot 2022-01-14 at 12 56 15 PM" src="https://user-images.githubusercontent.com/40220280/149584032-422b286f-3c1d-4ce8-93e5-bc43011c81ac.png">

To reproduce: 
1.) run ./mwaa-local-env build-image

Is there any other information that would help debug this issue?

**Comment by cdang1234** [comment]
It works now. 

The trick was I removed the constraints for prison and flask-openid from the constraints.txt file. But I'm sure this is not the right way to fix this. Curious to hear others' thoughts.

**Comment by asaf400** [comment]
https://github.com/aws/aws-mwaa-local-runner/issues/78#issuecomment-1005224068
