### ISSUE TITLE
How to config for aws credentials(using assum role, profile) in connection?

### ISSUE THREAD

**Issue by getz213** [aws/aws-mwaa-local-runner#81]
How to config for aws credentials(using assum role, profile) in connection?

I configured aws connection in airflow connect menu 

*  input value 
1) aws_default => extra 
 -  { "session_kwargs": {"profile_name": "my_profile"}, "region_name": "ap-northeast-2", "profile": "my_profile"}
 - already configured  aws clie -  "export AWS_DEFAULT_PROFILE=KE" in bashrc 
 - "aws s3 ls" command good work 
2) docker-compose-local.yml
 - Add  "- $HOME/.aws/credentials:/usr/local/airflow/.aws/credentials:ro"  
 
But not work aws access .... 

[Additional information]
I was above config to airflow docker image(apache airflow site provided) ... It is good work 
local runner image not work.. 

Please advise it

**Comment by mert-kurttutan** [comment]
Hi, 
One of the ways I used to set my aws credentials when running mwaa local is to write a bash script of the following form.

```
#!/bin/bash

# Credentials
aws configure set aws_access_key_id ${KEY_ID_TO_YOUR_ACCOUNT} --profile default
aws configure set aws_secret_access_key  ${ACCESS_KEY_TO_YOUR ACCOUNT} --profile default

```

Then I added a piece of code to add and run this script in DOCKERFILE. If you want more secure version of this, I guess you can use docker secrets to access key and key_id from the bash script.

**Comment by odette-ppb** [comment]
hello,

this worked for me:
in the docker compose file, try to add
`${PWD}/.aws:/usr/local/airflow/.aws`
instead of
` $HOME/.aws/credentials:/usr/local/airflow/.aws/credentials:ro`

in the .aws folder, you should have the credentials and the config.
you should have your .aws folder at the same level as your dags & plugins folders for this suggestion to work.

**Comment by john-jac** [comment]
Please use environment variables: https://github.com/aws/aws-mwaa-local-runner/pull/149
