### ISSUE TITLE
Local support for KubernetesPodOperator

### ISSUE THREAD

**Issue by peterdotcode** [aws/aws-mwaa-local-runner#82]
Looking for a solution to run the KubernetesPodOperator locally.

[From looking at the Using Amazon MWAA with Amazon](https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-eks-example.html#eksctl-kube-config
), as per the document I've added;
```
kubernetes
apache-airflow[cncf.kubernetes]==2.0.2
```
To -> `aws-mwaa-local-runner/docker/config/requirements.txt`

I've added the kube_config.yaml of my local Kubernetes cluster to the DAGS folder but get the error but when running the [example DAG](https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-eks-example.html#eksctl-create-dag) I get the error ;
`kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name aws in kube-config/contexts list`

Anyone able to point me in the right direction KubernetesPodOperator running locally?

**Comment by john-jac** [comment]
https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-eks-example.html#eksctl-requirements
