### ISSUE TITLE
Installing all dependencies on a virtual environment does not work - Setting the project Python Interpreter

### ISSUE THREAD

**Issue by miguellgramacho96** [aws/aws-mwaa-local-runner#84]
Hi!

I'm trying to install the dependencies that ships with the project (docker/config/requirements) + additional python dependencies from dags/requirements in a venv so I can point the Python Interpreter to it, but I can't get the dependencies installed (it throws some errors related to psycopg2).

Is anyone facing the same problem or have an alternative way to set up the Python Interpreter for the project?

Kind regards.

**Comment by kommuembroker** [comment]
Same here, How didi you resolve it?
