### ISSUE TITLE
Auto-importing variables and connections upon startup

### ISSUE THREAD

**Issue by kduvzc** [aws/aws-mwaa-local-runner#85]
Is there a suggested method for auto-importing variables and connections upon instance startup?

**Comment by mhadole-tc** [comment]
This could help

https://docs.aws.amazon.com/mwaa/latest/userguide/samples-env-variables.html

**Comment by tjvananne** [comment]
I'm also really interested in this. I might be misunderstanding the intent of that link above, but I don't think this is an environment variable issue but more of the "Airflow Variable" and "Airflow Connections" type of issue.

**Comment by john-jac** [comment]
Addressed in https://github.com/aws/aws-mwaa-local-runner/pull/149
