### ISSUE TITLE
DAGS won't execute

### ISSUE THREAD

**Issue by k-schmidt** [aws/aws-mwaa-local-runner#90]
Everything was built correctly. I've tested my requirements.txt but none of my DAGs will execute their tasks including the tutorial DAG bundled w/ the repo. It says the DAG is running but none of the tasks will start.
<img width="1775" alt="Screen Shot 2022-02-09 at 11 45 37 AM" src="https://user-images.githubusercontent.com/4649128/153278463-8087055c-29bf-4508-90b8-82fd2ef00349.png">

**Comment by kelvingakuo** [comment]
@k-schmidt I see you closed this. Did you get a solution? I'm running into the same problem
