### ISSUE TITLE
Merge `main` into the `v2.0.2` branch

### ISSUE THREAD

**Issue by SergiyKolesnikov** [aws/aws-mwaa-local-runner#91]
Please merge the `main` branch into the `v2.0.2` branch to fix the major bug #73 in that branch.

Versioned branches, such as `v2.0.2` is the only way to use aws-mwaa-local-runner in automation scripts, because the Airflow version is pinned (e.g., to 2.0.2). If we start using the `main` branch in automation scripts than at the point the `main` branch moves to the next Airflow version the automation will most certainty break, because of incompatible changes in the newer Airflow.

**Comment by john-jac** [comment]
Main branch is being depreciated, default is now 2.2.2
